#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo chown -R "$USER":"$USER" /var/www/
sudo chown -R "$USER":"$USER" /etc/nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html
line="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=ZUrZnux72zI permanent;"
sudo sed -i "26i $line" /etc/nginx/sites-available/default
sed -i '/listen 80 default_server;/a add_header X-Served-By $hostname;' /etc/nginx/sites-available/default
sudo service nginx restart
