#!/usr/bin/env bash
#Bash script that displays the content of the file /etc/passwd
IFS=':'
while read -r USERNAME PASSWORD USERID GROUPID USERIDINFO HOMEDIR COMMAND
do
    echo "The user $USERNAME is part of the $GROUPID gang, lives in $HOMEDIR and rides $COMMAND. $USERID's place is protected by the passcode $PASSWORD, more info about the user here: $USERIDINFO"
done < "/etc/passwd"
