#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
x=1
while [ $x -le 10 ]
do
    if test $x == 4
    then
        echo "bad luck"
    elif test $x == 8
    then
        echo "good luck"
    else
        echo "Holberton School"
    fi
    x=$(( $x + 1 ))
done
