#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
x=1
while [ $x -le 20 ]
do
    case $x in
    4)
        echo "$x"
        echo "bad luck from China"
        ;;
    9)
        echo "$x"
        echo "bad luck from Japan"
        ;;
    17)
        echo "$x"
        echo "bad luck from Italy"
        ;;
    *)
        echo "$x"
        ;;
    esac
    x=$(( x + 1 ))
done
