#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
x=0
while [ $x -le 12 ]
do
    echo "Hour: $x"
    i=1
    while [ $i -le 59 ]
    do
        echo "$i"
        i=$(( $i + 1 ))
    done
    x=$(( $x + 1 ))
done
