#!/usr/bin/env bash
# bash script that run whoami
sed -i 's/80/8080/' /etc/nginx/sites-enabled/default
chown nginx:nginx /etc/nginx/ -R
chmod +rw /etc/nginx/nginx.conf
pkill apache2
su -c 'service nginx start' nginx
